package integration

var UnifiedStationNameToStationIdMap = map[string]int{
	"aerodrom":             26,
	"albania":              -36,
	"bar":                  1,
	"baresumanovica":       51,
	"becici":               -28,
	"belgrad":              18,
	"belgrade":             18,
	"beograd":              18,
	"beogradcentar":        18,
	"bijelopolje":          7,
	"bioce":                28,
	"bosniaandherzegovina": -42,
	"bratonozici":          29,
	"budva":                -10,
	"cetinje":              -16,
	"crmnica":              21,
	"dabovici":             54,
	"danilovgrad":          49,
	"durmitor":             -20,
	"golubovci":            3,
	"hercegnovi":           -30,
	"indjija":              -2,
	"kolasin":              5,
	"kos":                  34,
	"kosjeric":             13,
	"kotor":                -14,
	"krusevackipotok":      31,
	"krusevo":              44,
	"lajkovac":             15,
	"lazarevac":            16,
	"ljesnica":             45,
	"ljutotuk":             48,
	"lutovo":               30,
	"matesevo":             35,
	"mijatovokolo":         41,
	"mojkovac":             6,
	"moraca":               25,
	"niksic":               56,
	"novapazova":           -6,
	"novisad":              0,
	"oblutak":              37,
	"ostrog":               53,
	"padez":                36,
	"perast":               -18,
	"petrovac":             -22,
	"podgorica":            4,
	"pozega":               12,
	"priboj":               10,
	"pricelje":             46,
	"prijepolje":           9,
	"prijepoljeteretna":    8,
	"rakovica":             17,
	"ravnarijeka":          43,
	"sarajevo":             -44,
	"savnik":               -32,
	"seliste":              33,
	"shkoder":              -40,
	"slap":                 50,
	"slijepacmost":         42,
	"sobajici":             52,
	"spuz":                 47,
	"starapazova":          -4,
	"stitarickarijeka":     39,
	"stubica":              55,
	"subotica":             -8,
	"susanj":               20,
	"sutomore":             2,
	"svetistefan":          -26,
	"tirana":               -38,
	"tivat":                -12,
	"trebaljevo":           38,
	"trebesica":            32,
	"ulcinj":               -24,
	"uzice":                11,
	"valjevo":              14,
	"virpazar":             22,
	"vranjina":             23,
	"zabljak":              -34,
	"zari":                 40,
	"zemun":                19,
	"zeta":                 24,
	"zlatica":              27,
	"албания":              -37,
	"аэродром":             26,
	"бар":                  1,
	"барешумановица":       51,
	"белградцентр":         18,
	"белополе":             7,
	"београдцентар":        18,
	"бечичи":               -29,
	"биоче":                28,
	"бијелопоље":           7,
	"боснияигерцеговина":   -43,
	"братоношичи":          29,
	"братоношићи":          29,
	"будва":                -11,
	"вальево":              14,
	"ваљево":               14,
	"вирпазар":             22,
	"враньина":             23,
	"врањина":              23,
	"голубовци":            3,
	"голубовцы":            3,
	"дабовичи":             54,
	"дабовићи":             54,
	"даниловград":          49,
	"дурмитор":             -21,
	"жабляк":               -35,
	"зари":                 40,
	"земун":                19,
	"зета":                 24,
	"златица":              27,
	"индия":                -3,
	"колашин":              5,
	"кос":                  34,
	"косерич":              13,
	"косјерић":             13,
	"котор":                -15,
	"крушевацкипоток":      31,
	"крушевачкипоток":      31,
	"крушево":              44,
	"лазаревац":            16,
	"лаиковац":             15,
	"лајковац":             15,
	"лутово":               30,
	"льешница":             45,
	"лютотук":              48,
	"матесево":             35,
	"матешево":             35,
	"миятовоколо":          41,
	"мијатовоколо":         41,
	"моиковац":             6,
	"морача":               25,
	"мојковац":             6,
	"никшич":               56,
	"никшић":               56,
	"новапазова":           -7,
	"новисад":              -1,
	"облутак":              37,
	"острог":               53,
	"падеж":                36,
	"пераст":               -19,
	"петровац":             -23,
	"подгорица":            4,
	"пожега":               12,
	"прибои":               10,
	"прибој":               10,
	"приеполье":            9,
	"приепольетеретна":     8,
	"прицеље":              46,
	"причелье":             46,
	"пријепоље":            9,
	"пријепољетеретна":     8,
	"равнарека":            43,
	"равнаријека":          43,
	"раковица":             17,
	"сараево":              -45,
	"светистефан":          -27,
	"селиште":              33,
	"слап":                 50,
	"слепецмост":           42,
	"слијепацмост":         42,
	"собајићи":             52,
	"спуж":                 47,
	"старапазова":          -5,
	"стубица":              55,
	"суботица":             -9,
	"сутоморе":             2,
	"тиват":                -13,
	"тирана":               -39,
	"требальево":           38,
	"требаљево":            38,
	"требешица":            32,
	"ужице":                11,
	"ульцин":               -25,
	"херцегнови":           -31,
	"цетине":               -17,
	"црмница":              21,
	"шавник":               -33,
	"шкодер":               -41,
	"шобаиичи":             52,
	"штитарицарека":        39,
	"штитаричкарека":       39,
	"шушань":               20,
	"шушањ":                20,
	"љешница":              45,
	"љутотук":              48,
}

type Station struct {
	Id         int
	ZpcgStopId int
	Type       int
	Name       string
	NameEn     string
	NameCyr    string
}

var StationIdToStationMap = map[int]Station{
	1: {
		Id:         1,
		ZpcgStopId: 1,
		Type:       4,
		Name:       "Bar",
		NameEn:     "Bar",
		NameCyr:    "Бар",
	},
	2: {
		Id:         2,
		ZpcgStopId: 3,
		Type:       1,
		Name:       "Sutomore",
		NameEn:     "Sutomore",
		NameCyr:    "Сутоморе",
	},
	3: {
		Id:         3,
		ZpcgStopId: 6,
		Type:       1,
		Name:       "Golubovci",
		NameEn:     "Golubovci",
		NameCyr:    "Голубовци",
	},
	4: {
		Id:         4,
		ZpcgStopId: 8,
		Type:       4,
		Name:       "Podgorica",
		NameEn:     "Podgorica",
		NameCyr:    "Подгорица",
	},
	5: {
		Id:         5,
		ZpcgStopId: 15,
		Type:       1,
		Name:       "Kolašin",
		NameEn:     "Kolašin",
		NameCyr:    "Колашин",
	},
	6: {
		Id:         6,
		ZpcgStopId: 18,
		Type:       1,
		Name:       "Mojkovac",
		NameEn:     "Mojkovac",
		NameCyr:    "Мојковац",
	},
	7: {
		Id:         7,
		ZpcgStopId: 22,
		Type:       4,
		Name:       "Bijelo Polje",
		NameEn:     "Bijelo Polje",
		NameCyr:    "Бијело Поље",
	},
	8: {
		Id:         8,
		ZpcgStopId: 55,
		Type:       1,
		Name:       "Prijepolje teretna",
		NameEn:     "Prijepolje cargo",
		NameCyr:    "Пријепоље теретна",
	},
	9: {
		Id:         9,
		ZpcgStopId: 26,
		Type:       2,
		Name:       "Prijepolje",
		NameEn:     "Prijepolje",
		NameCyr:    "Пријепоље",
	},
	10: {
		Id:         10,
		ZpcgStopId: 27,
		Type:       2,
		Name:       "Priboj",
		NameEn:     "Priboj",
		NameCyr:    "Прибој",
	},
	11: {
		Id:         11,
		ZpcgStopId: 28,
		Type:       2,
		Name:       "Užice",
		NameEn:     "Užice",
		NameCyr:    "Ужице",
	},
	12: {
		Id:         12,
		ZpcgStopId: 29,
		Type:       3,
		Name:       "Požega",
		NameEn:     "Požega",
		NameCyr:    "Пожега",
	},
	13: {
		Id:         13,
		ZpcgStopId: 62,
		Type:       1,
		Name:       "Kosjerić",
		NameEn:     "Kosjeric",
		NameCyr:    "Косјерић",
	},
	14: {
		Id:         14,
		ZpcgStopId: 30,
		Type:       2,
		Name:       "Valjevo",
		NameEn:     "Valjevo",
		NameCyr:    "Ваљево",
	},
	15: {
		Id:         15,
		ZpcgStopId: 66,
		Type:       1,
		Name:       "Lajkovac",
		NameEn:     "Lajkovac",
		NameCyr:    "Лајковац",
	},
	16: {
		Id:         16,
		ZpcgStopId: 65,
		Type:       1,
		Name:       "Lazarevac",
		NameEn:     "Lazarevac",
		NameCyr:    "Лазаревац",
	},
	17: {
		Id:         17,
		ZpcgStopId: 61,
		Type:       1,
		Name:       "Rakovica",
		NameEn:     "Rakovica",
		NameCyr:    "Раковица",
	},
	18: {
		Id:         18,
		ZpcgStopId: 31,
		Type:       4,
		Name:       "Beograd Centar",
		NameEn:     "Belgrade Center",
		NameCyr:    "Београд Центар",
	},
	19: {
		Id:         19,
		ZpcgStopId: 75,
		Type:       1,
		Name:       "Zemun",
		NameEn:     "Zemun",
		NameCyr:    "Земун",
	},
	20: {
		Id:         20,
		ZpcgStopId: 2,
		Type:       2,
		Name:       "Šušanj",
		NameEn:     "Šušanj",
		NameCyr:    "Шушањ",
	},
	21: {
		Id:         21,
		ZpcgStopId: 43,
		Type:       2,
		Name:       "Crmnica",
		NameEn:     "Crmnica",
		NameCyr:    "Црмница",
	},
	22: {
		Id:         22,
		ZpcgStopId: 4,
		Type:       1,
		Name:       "Virpazar",
		NameEn:     "Virpazar",
		NameCyr:    "Вирпазар",
	},
	23: {
		Id:         23,
		ZpcgStopId: 44,
		Type:       2,
		Name:       "Vranjina",
		NameEn:     "Vranjina",
		NameCyr:    "Врањина",
	},
	24: {
		Id:         24,
		ZpcgStopId: 5,
		Type:       3,
		Name:       "Zeta",
		NameEn:     "Zeta",
		NameCyr:    "Зета",
	},
	25: {
		Id:         25,
		ZpcgStopId: 45,
		Type:       2,
		Name:       "Morača",
		NameEn:     "Morača",
		NameCyr:    "Морача",
	},
	26: {
		Id:         26,
		ZpcgStopId: 7,
		Type:       2,
		Name:       "Aerodrom",
		NameEn:     "Aerodrom",
		NameCyr:    "Аеродром",
	},
	27: {
		Id:         27,
		ZpcgStopId: 9,
		Type:       2,
		Name:       "Zlatica",
		NameEn:     "Zlatica",
		NameCyr:    "Златица",
	},
	28: {
		Id:         28,
		ZpcgStopId: 46,
		Type:       3,
		Name:       "Bioče",
		NameEn:     "Bioče",
		NameCyr:    "Биоче",
	},
	29: {
		Id:         29,
		ZpcgStopId: 10,
		Type:       3,
		Name:       "Bratonožići",
		NameEn:     "Bratonožići",
		NameCyr:    "Братоножићи",
	},
	30: {
		Id:         30,
		ZpcgStopId: 11,
		Type:       3,
		Name:       "Lutovo",
		NameEn:     "Lutovo",
		NameCyr:    "Лутово",
	},
	31: {
		Id:         31,
		ZpcgStopId: 47,
		Type:       2,
		Name:       "Kruševački Potok",
		NameEn:     "Kruševački Potok",
		NameCyr:    "Крушевачки Поток",
	},
	32: {
		Id:         32,
		ZpcgStopId: 12,
		Type:       1,
		Name:       "Trebešica",
		NameEn:     "Trebešica",
		NameCyr:    "Требешица",
	},
	33: {
		Id:         33,
		ZpcgStopId: 13,
		Type:       2,
		Name:       "Selište",
		NameEn:     "Selište",
		NameCyr:    "Селиште",
	},
	34: {
		Id:         34,
		ZpcgStopId: 48,
		Type:       3,
		Name:       "Kos",
		NameEn:     "Kos",
		NameCyr:    "Кос",
	},
	35: {
		Id:         35,
		ZpcgStopId: 14,
		Type:       2,
		Name:       "Mateševo",
		NameEn:     "Mateševo",
		NameCyr:    "Матешево",
	},
	36: {
		Id:         36,
		ZpcgStopId: 49,
		Type:       2,
		Name:       "Padež",
		NameEn:     "Padež",
		NameCyr:    "Падеж",
	},
	37: {
		Id:         37,
		ZpcgStopId: 16,
		Type:       2,
		Name:       "Oblutak",
		NameEn:     "Oblutak",
		NameCyr:    "Облутак",
	},
	38: {
		Id:         38,
		ZpcgStopId: 50,
		Type:       3,
		Name:       "Trebaljevo",
		NameEn:     "Trebaljevo",
		NameCyr:    "Требаљево",
	},
	39: {
		Id:         39,
		ZpcgStopId: 17,
		Type:       2,
		Name:       "Štitarička Rijeka",
		NameEn:     "Štitarička Rijeka",
		NameCyr:    "Штитаричка Ријека",
	},
	40: {
		Id:         40,
		ZpcgStopId: 51,
		Type:       2,
		Name:       "Žari",
		NameEn:     "Žari",
		NameCyr:    "Жари",
	},
	41: {
		Id:         41,
		ZpcgStopId: 19,
		Type:       3,
		Name:       "Mijatovo Kolo",
		NameEn:     "Mijatovo Kolo",
		NameCyr:    "Мијатово Коло",
	},
	42: {
		Id:         42,
		ZpcgStopId: 52,
		Type:       2,
		Name:       "Slijepač Most",
		NameEn:     "Slijepač Most",
		NameCyr:    "Слијепач Мост",
	},
	43: {
		Id:         43,
		ZpcgStopId: 53,
		Type:       2,
		Name:       "Ravna Rijeka",
		NameEn:     "Ravna Rijeka",
		NameCyr:    "Равна Ријека",
	},
	44: {
		Id:         44,
		ZpcgStopId: 20,
		Type:       3,
		Name:       "Kruševo",
		NameEn:     "Kruševo",
		NameCyr:    "Крушево",
	},
	45: {
		Id:         45,
		ZpcgStopId: 21,
		Type:       2,
		Name:       "Lješnica",
		NameEn:     "Lješnica",
		NameCyr:    "Љешница",
	},
	46: {
		Id:         46,
		ZpcgStopId: 35,
		Type:       2,
		Name:       "Pričelje",
		NameEn:     "Pričelje",
		NameCyr:    "Причеље",
	},
	47: {
		Id:         47,
		ZpcgStopId: 23,
		Type:       1,
		Name:       "Spuž",
		NameEn:     "Spuž",
		NameCyr:    "Спуж",
	},
	48: {
		Id:         48,
		ZpcgStopId: 36,
		Type:       2,
		Name:       "Ljutotuk",
		NameEn:     "Ljutotuk",
		NameCyr:    "Љутотук",
	},
	49: {
		Id:         49,
		ZpcgStopId: 24,
		Type:       4,
		Name:       "Danilovgrad",
		NameEn:     "Danilovgrad",
		NameCyr:    "Даниловград",
	},
	50: {
		Id:         50,
		ZpcgStopId: 37,
		Type:       2,
		Name:       "Slap",
		NameEn:     "Slap",
		NameCyr:    "Слап",
	},
	51: {
		Id:         51,
		ZpcgStopId: 38,
		Type:       2,
		Name:       "Bare Šumanovića",
		NameEn:     "Bare Šumanovića",
		NameCyr:    "Баре Шумановића",
	},
	52: {
		Id:         52,
		ZpcgStopId: 39,
		Type:       2,
		Name:       "Šobajići",
		NameEn:     "Šobajići",
		NameCyr:    "Шобајићи",
	},
	53: {
		Id:         53,
		ZpcgStopId: 40,
		Type:       3,
		Name:       "Ostrog",
		NameEn:     "Ostrog",
		NameCyr:    "Острог",
	},
	54: {
		Id:         54,
		ZpcgStopId: 41,
		Type:       2,
		Name:       "Dabovići",
		NameEn:     "Dabovići",
		NameCyr:    "Дабовићи",
	},
	55: {
		Id:         55,
		ZpcgStopId: 42,
		Type:       2,
		Name:       "Stubica",
		NameEn:     "Stubica",
		NameCyr:    "Стубица",
	},
	56: {
		Id:         56,
		ZpcgStopId: 25,
		Type:       4,
		Name:       "Nikšić",
		NameEn:     "Nikšić",
		NameCyr:    "Никшић",
	},
	57: {
		Id:         57,
		ZpcgStopId: 32,
		Type:       4,
		Name:       "Novi Sad",
		NameEn:     "Novi Sad",
		NameCyr:    "Нови Сад",
	},
	58: {
		Id:         58,
		ZpcgStopId: 33,
		Type:       2,
		Name:       "Vrbas",
		NameEn:     "Vrbas",
		NameCyr:    "Врбас",
	},
	59: {
		Id:         59,
		ZpcgStopId: 34,
		Type:       4,
		Name:       "Subotica",
		NameEn:     "Subotica",
		NameCyr:    "Суботица",
	},
	60: {
		Id:         60,
		ZpcgStopId: 54,
		Type:       1,
		Name:       "Novi Beograd",
		NameEn:     "Novi Beograd",
		NameCyr:    "Нови Београд",
	},
	61: {
		Id:         61,
		ZpcgStopId: 56,
		Type:       1,
		Name:       "Čačak",
		NameEn:     "Čačak",
		NameCyr:    "Чачак",
	},
	62: {
		Id:         62,
		ZpcgStopId: 57,
		Type:       1,
		Name:       "Kraljevo",
		NameEn:     "Kraljevo",
		NameCyr:    "Краљево",
	},
	63: {
		Id:         63,
		ZpcgStopId: 58,
		Type:       1,
		Name:       "Kragujevac",
		NameEn:     "Kragujevac",
		NameCyr:    "Крагујевац",
	},
	64: {
		Id:         64,
		ZpcgStopId: 59,
		Type:       1,
		Name:       "Lapovo",
		NameEn:     "Lapovo",
		NameCyr:    "Лапово",
	},
	65: {
		Id:         65,
		ZpcgStopId: 60,
		Type:       1,
		Name:       "Velika Plana",
		NameEn:     "Velika Plana",
		NameCyr:    "Велика Плана",
	},
	66: {
		Id:         66,
		ZpcgStopId: 63,
		Type:       1,
		Name:       "Branešci",
		NameEn:     "Branesci",
		NameCyr:    "Бранешци",
	},
	67: {
		Id:         67,
		ZpcgStopId: 64,
		Type:       1,
		Name:       "Brodarevo",
		NameEn:     "Brodarevo",
		NameCyr:    "Бродарево",
	},
	68: {
		Id:         68,
		ZpcgStopId: 67,
		Type:       1,
		Name:       "Vrbnica",
		NameEn:     "Vrbnica",
		NameCyr:    "Врбница",
	},
	69: {
		Id:         69,
		ZpcgStopId: 68,
		Type:       1,
		Name:       "Zmajevo",
		NameEn:     "Zmajevo",
		NameCyr:    "Змајево",
	},
	70: {
		Id:         70,
		ZpcgStopId: 69,
		Type:       1,
		Name:       "Inđija",
		NameEn:     "Indjija",
		NameCyr:    "Инђија",
	},
	71: {
		Id:         71,
		ZpcgStopId: 70,
		Type:       1,
		Name:       "Stara Pazova",
		NameEn:     "Stara Pazova",
		NameCyr:    "Стара Пазова",
	},
	72: {
		Id:         72,
		ZpcgStopId: 71,
		Type:       1,
		Name:       "Nova Pazova",
		NameEn:     "Nova Pazova",
		NameCyr:    "Нова Пазова",
	},
	73: {
		Id:         73,
		ZpcgStopId: 72,
		Type:       1,
		Name:       "Lovćenac",
		NameEn:     "Lovcenac",
		NameCyr:    "Ловћенац",
	},
	74: {
		Id:         74,
		ZpcgStopId: 73,
		Type:       2,
		Name:       "Beška",
		NameEn:     "Beska",
		NameCyr:    "Бешка",
	},
	75: {
		Id:         75,
		ZpcgStopId: 74,
		Type:       2,
		Name:       "Bačka Topola",
		NameEn:     "Backa Topola",
		NameCyr:    "Бачка Топола",
	},
}

type StationAliases struct {
	StationName string
	Aliases     []string
}

var AliasesStationsList = []StationAliases{
	{
		StationName: "Beograd Centar",
		Aliases:     []string{"Beograd", "belgrad", "belgrade", "Београд Центар", "Белград Центр"},
	},

	//summer period aliases
	{
		StationName: "Novi Sad",
		Aliases:     []string{"Нови сад", "Новый Сад"},
	},
	{
		StationName: "Novi Beograd",
		Aliases:     []string{"Novi Beograd", "Novi belgrad", "New Belgrade", "Нови Београд", "Новый Белград"},
	},
	{
		StationName: "Stara Pazova",
		Aliases:     []string{"Стара Пазова"},
	},
	{
		StationName: "Nova Pazova",
		Aliases:     []string{"Нова Пазова"},
	},
	//summer period aliases

	{
		StationName: "Bar",
		Aliases:     []string{"Бар"},
	},
	{
		StationName: "Sutomore",
		Aliases:     []string{"Сутоморе"},
	},
	{
		StationName: "Golubovci",
		Aliases:     []string{"Голубовци", "Голубовцы"},
	},
	{
		StationName: "Podgorica",
		Aliases:     []string{"Подгорица"},
	},
	{
		StationName: "Kolašin",
		Aliases:     []string{"Колашин"},
	},
	{
		StationName: "Mojkovac",
		Aliases:     []string{"Мојковац", "Мойковац"},
	},
	{
		StationName: "Bijelo Polje",
		Aliases:     []string{"Бијело Поље", "Бело Поле"},
	},
	{
		StationName: "Prijepolje teretna",
		Aliases:     []string{"Пријепоље теретна", "Приеполье теретна"},
	},
	{
		StationName: "Prijepolje",
		Aliases:     []string{"Пријепоље", "Приеполье"},
	},
	{
		StationName: "Priboj",
		Aliases:     []string{"Прибој", "Прибой"},
	},
	{
		StationName: "Užice",
		Aliases:     []string{"Ужице"},
	},
	{
		StationName: "Požega",
		Aliases:     []string{"Пожега"},
	},
	{
		StationName: "Kosjerić",
		Aliases:     []string{"Косјерић", "Косерич"},
	},
	{
		StationName: "Valjevo",
		Aliases:     []string{"Ваљево", "Вальево"},
	},
	{
		StationName: "Lajkovac",
		Aliases:     []string{"Лајковац", "Лайковац"},
	},
	{
		StationName: "Lazarevac",
		Aliases:     []string{"Лазаревац", "Лазаревац"},
	},
	{
		StationName: "Rakovica",
		Aliases:     []string{"Раковица", "Раковица"},
	},
	{
		StationName: "Zemun",
		Aliases:     []string{"Земун"},
	},
	{
		StationName: "Šušanj",
		Aliases:     []string{"Шушањ", "Шушань"},
	},
	{
		StationName: "Crmnica",
		Aliases:     []string{"Црмница"},
	},
	{
		StationName: "Virpazar",
		Aliases:     []string{"Вирпазар"},
	},
	{
		StationName: "Vranjina",
		Aliases:     []string{"Врањина", "Враньина"},
	},
	{
		StationName: "Zeta",
		Aliases:     []string{"Зета"},
	},
	{
		StationName: "Morača",
		Aliases:     []string{"Морача"},
	},
	{
		StationName: "Aerodrom",
		Aliases:     []string{"аэродром"},
	},
	{
		StationName: "Zlatica",
		Aliases:     []string{"Златица"},
	},
	{
		StationName: "Bioče",
		Aliases:     []string{"Биоче"},
	},
	{
		StationName: "Bratonožići",
		Aliases:     []string{"Братоношићи", "Братоношичи"},
	},
	{
		StationName: "Lutovo",
		Aliases:     []string{"Лутово"},
	},
	{
		StationName: "Kruševački Potok",
		Aliases:     []string{"Крушевачки поток", "Крушевацки поток"},
	},
	{
		StationName: "Trebešica",
		Aliases:     []string{"Требешица"},
	},
	{
		StationName: "Selište",
		Aliases:     []string{"Селиште"},
	},
	{
		StationName: "Kos",
		Aliases:     []string{"Кос"},
	},
	{
		StationName: "Mateševo",
		Aliases:     []string{"Матешево", "Матесево"},
	},
	{
		StationName: "Padež",
		Aliases:     []string{"Падеж"},
	},
	{
		StationName: "Oblutak",
		Aliases:     []string{"Облутак"},
	},
	{
		StationName: "Trebaljevo",
		Aliases:     []string{"Требаљево", "Требальево"},
	},
	{
		StationName: "Štitarička Rijeka",
		Aliases:     []string{"Штитарица река", "Штитаричка река"},
	},
	{
		StationName: "Žari",
		Aliases:     []string{"Зари", "Зари"},
	},
	{
		StationName: "Mijatovo Kolo",
		Aliases:     []string{"Мијатово коло", "Миятово коло"},
	},
	{
		StationName: "Slijepač Most",
		Aliases:     []string{"Слијепац мост", "Слепец мост"},
	},
	{
		StationName: "Ravna Rijeka",
		Aliases:     []string{"Равна ријека", "Равна река"},
	},
	{
		StationName: "Kruševo",
		Aliases:     []string{"Крушево"},
	},
	{
		StationName: "Lješnica",
		Aliases:     []string{"Љешница", "Льешница"},
	},
	{
		StationName: "Pričelje",
		Aliases:     []string{"Прицеље", "Причелье"},
	},
	{
		StationName: "Spuž",
		Aliases:     []string{"Спуж"},
	},
	{
		StationName: "Ljutotuk",
		Aliases:     []string{"Љутотук", "Лютотук"},
	},
	{
		StationName: "Danilovgrad",
		Aliases:     []string{"Даниловград"},
	},
	{
		StationName: "Slap",
		Aliases:     []string{"Слап"},
	},
	{
		StationName: "Bare Šumanovića",
		Aliases:     []string{"Баре Шумановица"},
	},
	{
		StationName: "Šobajići",
		Aliases:     []string{"Собајићи", "Шобайичи"},
	},
	{
		StationName: "Ostrog",
		Aliases:     []string{"Острог"},
	},
	{
		StationName: "Dabovići",
		Aliases:     []string{"Дабовићи", "Дабовичи"},
	},
	{
		StationName: "Stubica",
		Aliases:     []string{"Стубица"},
	},
	{
		StationName: "Nikšić",
		Aliases:     []string{"Никшић", "Никшич"},
	},
}

var BlackListedStations = []struct {
	Names []string
}{
	{
		Names: []string{"Budva", "Будва"},
	},
	{
		Names: []string{"Tivat", "Тиват"},
	},
	{
		Names: []string{"Kotor", "Котор"},
	},
	{
		Names: []string{"Cetinje", "Цетине"},
	},
	{
		Names: []string{"Perast", "Пераст"},
	},
	{
		Names: []string{"Durmitor", "Дурмитор"},
	},
	{
		Names: []string{"Petrovac", "Петровац"},
	},
	{
		Names: []string{"Ulcinj", "Ульцин"},
	},
	{
		Names: []string{"Sveti Stefan", "Свети Стефан"},
	},
	{
		Names: []string{"Becici", "Бечичи"},
	},
	{
		Names: []string{"Herceg Novi", "Херцег Нови"},
	},
	{
		Names: []string{"Savnik", "Шавник"},
	},
	{
		Names: []string{"Zabljak", "Жабляк"},
	},
	{
		Names: []string{"Albania", "Албания", "Tirana", "Тирана", "Shkoder", "Шкодер"},
	},
	{
		Names: []string{"Bosnia and Herzegovina", "Босния и Герцеговина", "Sarajevo", "Сараево"},
	},
}
